### ISSUE TITLE
Error starting backend due to local import

### ISSUE THREAD

**Issue by RaduNico** [RaduNico/psknow#11]
Trying to start backend using gunicorn results in following error

```
$ gunicorn3 -t 900 --workers 2 --bind 127.0.0.1:9645 wsgi --access-logfile logs/access.log --error-logfile logs/errors.log -c gunicorn_config.py
Failed to read config file: gunicorn_config.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 93, in get_config_from_filename
    execfile_(filename, cfg, cfg)
  File "/usr/lib/python3/dist-packages/gunicorn/_compat.py", line 72, in execfile_
    return six.exec_(code, *args)
  File "gunicorn_config.py", line 1, in <module>
    from source.config import Configuration
ModuleNotFoundError: No module named 'source'
```

This issue is solved by running `export PYTHONPATH='.'`. It could be solved by appending `.` in the PYTHONPATH from the gunicorn_config.py file

**Comment by RaduNico** [comment]
Solved in #17
